#!/bin/bash

# Copyright (c) 2013-2014 Artem Shinkarov <artyom.shinkaroff@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

set -e

script_name=$(basename $0)
params=$(getopt \
         -o vnbdIup:els:z:h \
         -l version,nofork,beep,dpms,inactivity-timeout,no-unlock-indicator,pointer:,ignore-empty-password,logo,screens:,size:,help \
         -n "$script_name" -- "$@")
eval set -- "$params"
# exit on bad argyments
if [ $? -ne 0 ]; then
    exit 1
fi

usage () {
    cat <<EOF
A wrapper around i3lock that sets a blurred screenshot
as a background image for the screen saver.

Usage: $script_name [options]

    -v, --version               version of the i3lock.
    -n, --nofork                don't fork i3lock after start.
    -b, --beep                  enable beeping.
    -d, --dpms                  enable turning off the screen with DPMS.
    -I, --inactivity-timeout    specifies  the  number of seconds i3lock will
                                wait for another password before turning
                                off the monitors.
    -u, --no-unlock-indicator   disable the unlock indicator.
    -p win|default, 
    --pointer=win|default       do not hide the mouse pointer on default
                                or the current position of the mouse pointer.
    -e, --ignore-empty-password when an empty password is provided by the user,
                                do  not  validate  it.

    Please note, that all the options except those listed below are being passed
    directly to i3lock.  See "man i3lock" for more details.

    -l, --logo                  superimpose the padlock logo
    -s NUM, --screens=NUM       the number(NUM) of screen to split by (useful with --logo)
    -z NUM, --size=NUM          the size(NUM percentage) of the padlock
                                relative to screen hight

EOF
}

arg_test () { 
    # Filter out arguments that are invalid
    while true; do
       case "$1" in
           -v|--version)
               i3lock -v
               exit
               ;;
           -n|--nofork)
               shift;;
           -b|--beep)
               shift;;
           -d|--dpms)
               shift;;
           -I|--inactivity-timeout)
               shift;;
           -u|--no-unlock-indicator)
               shift;;
           -p|--pointer) 
               shift
               case "$1" in
                   win|default)
                       shift;;
                   *)
                       echo "$script_name: invalid option \"$1\" for argument -p" >&2
                       exit 1
                       ;;
               esac
               ;;
           -e|--ignore-empty-password)
               shift;;
           -l|--logo)
               use_logo=1
               shift;;
           -s|--screens)
               __option__="$1"
               shift
               if [ "$1" -ge "1" ]; then
                   screens="$1"
                   shift
               else
                   echo "$script_name: invalid option \"$1\" for argument $__option__" >&2
                   exit 1
               fi
               ;;
           -z|--size)
               __option__="$1"
               shift
               if [ "$1" -ge "0" ] &>/dev/null && [ "$1" -le "100" ] &>/dev/null; then
                   scale=$(echo "$1 * .01" | bc)
                   shift
               else
                   echo "$script_name: invalid option \"$1\" for argument $__option__ (must be >= 0 && <= 100)" >&2
                   exit 1
               fi
               ;;
           -h|--help)
               usage
               exit
               ;;
           --)
               shift 
               break ;;

           *)
               echo "$script_name: invalid argument \"$1\"" >&2
               exit 1
               ;;
       esac
    done

    if [ $# -ne 0 ]; then
       echo "$script_name: invalid arguments \"$@\""
       exit 1
    fi
}

# This is a gzipped i3lock-icon.svg converted into pdf with base64 applied
img_pdf_gz () {
    cat <<EOF
H4sICIpVLFUAA3BhZC1sb2NrLXNpbXBsZS5wZGYAUw1wcdM11DPlUt36dt1vLmMFA4X8pCwuGxsF
fZ/UvPSSDAUToFAQl4KCgr5bZk5JahGQzkksSXVJTc5PSeWys+MqLilKTczlqpjTGuKYF2rIc2d/
8A+mlhsbH1ecZuPsdL2pJPZCuevC+0UbHvzqmRu+UndF6NV9tz4defxR5bt7/pozdi/v19fdvXR7
/dy8+v0hX17a/vu+9MvzhF8N9+cff67vUfqrTKN2SXXSqx+Vk+UFM9VOLSrZaZ22JXPyjMVfA3Yt
zsw9sWhGb+WFV76mJ9y5yx/ZzeLz6tHbJXA655R0kcDrrGX7DH1yLk07ztaZsrNy8jtW6Y0ME7Ki
Dgi6Mvn2C59qUOk19HuiIaeoPkGu0H+deJW7+fqMn7M6uIX2LRAz3i7RrfbDsdH60ULdZRdletXV
jHKfdcucUWPb3GpVs9ukM+WExpeCHo0ZlU17zqX1TMzJ2brEXDLb2X2V2GIrkaKFl7U+cl//euKc
8ZsjC20eby074xZ+yHFd0PEHMfPX8q8LVum68WKbo/un19cKrB7tc1jF3N36dMeKKrO/rXUOAiu9
dHx++zgyJOqwdiZWNjVNS7NgnvdiL6/5oQ2nKpkqDgSI/eiOvDIxrCvu9DmlRqcbDKsX3jhVK+r8
OvvgGe+SNlmhtrA3bNZTjmiUFMy4fXt6LOfyJdNeHl4jcsa0yDaudU6xmvfm4ljFD9veT4wsXLnn
WOGbzze//Bd9Uuq/bI3NQ5Mb+d4nUn95bQhWOLKuJT1acMuBWI+qWXK6haoirwpcuPkM3p4t4GF+
KvFL0eXmq9B6tQ1H+o6Yrl+tH8G4esO8TXpfPnP+lXndsFyrWd/ap/lax7ETyszHPvGY8m7v+rf0
kQfTNZbXXnI7Lu34/uJ16gZTQ5nk6OjHMcHnf7pJS0xvN9/OymIz+Xf7s5dHW92Te41WGonN0i2N
1z+S9MNJ6uRNo2OhiQEfd4nM1Jz6KfdUouDsm4HOHvFTZyhMNF6/VTFolkZPoeuTn48M5lltDNGd
r/Gl/sLHijlWW+umNHJMrAssOWytZSBxWNZmUcZTo8/bFrxmKG192HJRwF+Bextj5WWeifNqk6a9
3bH828+6OzL1jCZvLVm5UvNSoCkcyALlDRNoHgFmCXMjc5ioETzngPOKa0WJe3AJMJ8oQARAYokG
CqB85eyoYKign5wIJIG5BygBJIEIao4pUg4MqSxIVdAPSExPBZsZkFiUmlcC1AbLkL6pKZmJTvkV
CtFAIQMFIyMjPVNjE1NzMwjTyMTQyEQhFqzUOT+vBKi5WMEYrtu9KL+0AMl5ENvAojChYKBoUWJe
cQHI5uRKmLCnQklRaSqM5wxU5ZJalpmcGuTuBPUPSDwotTi/tCg5tVjBCGwnwo+GWP1YDNblnZlS
DPQPKBiC4G4vBXkbyQAzJAOcgXFTkl+koJGcmFmUr2CoZ2iiZ6SgkVFSUmClrw8WTC9KLMjITC7W
yy9K19SEhGVRfkppciop2hDWm2O43zmxJDEnPx0aTUC/QGMJoaeiKDWNy0DBgssADhTMTE2NTRXS
FKBihoYmQF1gmTyYmIEFFjEDQ1NMdYaWGGKWhsboYoZGBmYYYsbGSOpKihIzc1KLwJ4LzqxKBToZ
HJv5+SUK5vDE45mXlq9gBvNjcUliUQnYh4bGFsC6RNXV340LAH9CX5BbBgAA
EOF
}

superimpose_padlock() {
    scale=.8
    lockimage=$(mktemp --tmpdir i3lock-logo-XXXXXXXXXX)
    img_pdf_gz | base64 -d | gunzip > "${lockimage}.pdf"
    height=$(identify -format "($scale * %H + .5)/1\n" "$file2" | bc)     
    width=$(identify -format "scale=4; t=%W/%H; scale=0; (t * $height + .5)/1\n" "${lockimage}.pdf" | bc)
    convert -density 600 -background none -resize ${height}x${width} "${lockimage}.pdf" "${lockimage}.png"
    convert -compose Exclusion -composite -gravity center "$file2" "${lockimage}.png" "$file2"
    rm "${lockimage}" "${lockimage}.png" "${lockimage}.pdf"
}

use_logo=0
screens=1
scale=.43
arg_test $@

file1=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
file2=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)

screen_height=$(identify -format "(%H + .5)/1\n" "$file" | bc)
screen_width=$(identify -format "(%W + .5)/1\n" "$file" | bc)

if [ $use_logo -eq 1 ]; then
    superimpose_padlock
fi

cmd=()
for i in $@; do
    if [[ $i != '-l'  &&  $i != '--logo' && $i != '--' ]]; then
        case "$i" in
            -s|--screens|-z|--size)
                i=("${i[@]:2}")
                ;;
            *)
                cmd+="$i "
                ;;
        esac
    fi
done

# drop the last "--" introduced by getopt
i3lock -i "$file2" ${cmd}

trap "rm '$file2'" EXIT
